import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
import { Navbar } from "@repo/ui/navbar";
import { LeftNav } from "../../components/LeftNav";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <div className="h-screen w-screen md:grid md:grid-cols-12">
          <div className="md:grid md:col-span-2">
            <LeftNav />
          </div>

          <div className="md:grid md:col-span-10 h-full w-full flex flex-col jusitfy-start items-start bg-slate-50">
            <div className="h-full">
              <div className="">
                <Navbar appName="user-app" balance="1099.87" />
              </div>
              <div>
                {children}
              </div>
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
