import type { Metadata } from "next";
import localFont from "next/font/local";
// import "./globals.css";
import React from "react";
import { Provider } from "../provider";
import { Inter } from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css" rel="stylesheet" />
      </head>
      <Provider>
        <body className={inter.className}>
          {children}
          <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.js"></script>
        </body>
      </Provider>
    </html>
  );
}
